### Never 타입?
모든 함수는 값을 리턴하고 CPU 제어권을 리턴한다.
Void 함수도 사실 () 라는 빈 튜플을 리턴한다.

Never 타입은 CPU 제어권을 '절대' 리턴하지 않는다.
그래서 스택 프레임이 종료되어도 `main()`으로 CPU가 돌아가지 않아서 앱이 멈춘다.
비동기처리를 하면서 각 쓰레드를 사용할 때, 메인 제어권은 즉각 메인으로 돌아온다.
2번 쓰레드는 다른 CPU를 제어하면서 전달받은 작업을 진행할 것.

함수 내부에서 프로그램을 종료시키거나 할 때 사용한다.
이를 통해 에러를 미리 발견하고 검증하거나 테스트할 수 있다. 

**`assert()` 디버그 모드 검증 함수와 `precondition()` 출시 모드 검증 함수가 검증 함수로서 역할한다.**
assert() 함수는 출시 전에 어떻게든 오류를 발견하고자 하는 게 목적이다.
이 검증 함수도 함수 내에서 앱을 종료시킨다.

실제 앱 사용 환경에서는 별별 에러가 다 발생할 수 있다.
그래서 모든 상황을 검토하는 과정이 출시 이전 앱에서 이루어져야 한다.
이 테스트가 다 통과되어야만 출시가 가능하다.

추가로 앱을 실제로 출시할 때에는 `fatalError()` 메소드는 꼭 삭제해야 한다.
앱이 강제로 꺼질 수 있는 불씨를 안고 출시할 수는 없잖아.

항상 에러를 던져서 `catch` 문에서 처리하도록 해야 한다(제어권을 catch로 던지는 것).
근데 이렇게 하기보다는 위의 검증 함수를 쓰는 편.

Never 타입은 임시적으로 쓰이는 타입이다.
그 내부는 빈 열거형으로 정의되어 있고 인스턴스를 생성할 수 없다.

```swift
func add(a: Int, b: Int) -> Int {
    var c = a + b
    return c
}

var num1 = 5
var num2 = 3

var num3 = add(a: num1, b: num2)
print(num3) // 8

func crash() -> Never {
    fatalError("프로그램 멈춰!!")
}

```
---
### fatalError()

```swift
func fatalError(_ message: @autoclosure () -> String = String(),
    file: StaticString = #file, line: UInt = #line) -> Never {}

func someFatalErr() {
    fatalError("종료")
}

someFatalErr() // Fatal error message. 파일 이름과 코드의 위치까지 알려줌
```

### 디버깅 함수
아래 5개의 함수가 있다.

- assert()
    + `assert()`를 디버그 모드에서 작동하면 앱이 어떤 버그로 인해 꺼지는지 확인이 잘 된다.
    + 재밌는 건 출시 모드에서는 `assert()`가 비활성화 되어서 일일이 지우지 않아도 된다는 장점이 있다.
- assertionFailure()
- precondition()
    + 심각한 상황에서의 검증 함수라서 출시 버전의 앱에서도 앱을 멈춘다.
    + 유저에게 불편을 주더라도! 앱을 종료해야 하는 경우에 쓴다.
    + **테스트 모드에서는 동작하지 않는다.**
    + ex) 앱 업데이트가 되지 않은 상태로 앱을 쓰는 경우, 네트워크 통신이 망가질 수 있어서 강제 종료가 필요하다던가
- preconditionFailure()
- fatalError()
    + 아주 강력한 Never Type 함수이며 그 어떤 버전에서도 동작하여 앱을 종료시킨다.
    + 앵간하면 쓰지 않는다.
   
--- 
### 사용 예시
에러를 찾아서 고치는 건 좋은데... 꼭 앱을 꺼야 할까?
양수를 써야 하는 `TextField`에 음수를 넣는 게.. 앱을 강제종료할 일일까?

```swift
func enter() {
    let someWrongInput = -1
    assert(someWrongInput > 0, message: "잘못된 숫자를 입력!")
}

enter() // Assertion failed: 잘못된 숫자를 입력!

func enter2() {
    let someWrongInput = -1
    if someWrongInput > 0 {
        // 정상 코드
    } else {
        // 에러 케이스
        assertionFailure("잘못된 숫자를 입력!")
    }
}

enter2() // Fatal error: 잘못된 숫자를 입력!

// precondition()은 assert()와 아주 유사하다.
// 사용할 모드의 차이가 있을 뿐
func enter3() {
    let update = false
    precondition(update, "앱이 업데이트되지 않음")
}
```
---
### 에러의 관점에서
런타임 오류를 Error분기를 나누어서 처리했었지.
프로그래머가 제어 불가능한 영역에 대해 올바르게 처리해서 앱을 강제로 꺼지는 걸 방지할 수 있다.
만약 앱 업데이트가 되지 않았으면? 얼럿을 띄우고 종료시킬 수 있다.

그런데 assert() 등의 검증 함수를 통해서 개선하면 앱의 완성도가 더 높아질거야.
디버그 모드에서 검증하는 거지.

precondition() 함수를 쓰면 앱이 업데이트 되지 않을 때 곧바로 종료시킬 수 있다.
근데 얼럿이 없다면... 사용성이 떨어지지 않을까?
그니까 결론은 디버그 함수를 최대한 많이 써서 에러를 잘 핸들링하자는 거야.